### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by bit-cloner** [beefsack/script-httpd#1]
Really Nice , would be even better if it serves on websockets. Accepting user input on the fly. It will then become a true terminal in browser.

**Comment by beefsack** [comment]
Thanks for the kind words and the feature request @bit-cloner!

If I do a streaming version which could support websockets, I'll do it as a separate tool, because it will work substantially different to how this currently works. Namely because the current version waits for the script to finish executing so it can send an appropriate status code (200 or 500), however a streaming version would need to start sending responses immediately.
