### ISSUE TITLE
Serving of simple text not updating in Docker, cached text displayed instead

### ISSUE THREAD

**Issue by mihaigalos** [beefsack/script-httpd#15]
Using webify in docker, I'm seeing cached values for simple text:

`script.sh`:
```bash
#!/bin/sh

echo foo
```
```bash
docker run -d --rm -p 8080:80 -v  $(realpath script.sh):/script beefsack/webify
```
If I change `foo` to `bar`, `curl http://localhost:8080` still displays the old value.

This only occurs in Docker, if I run webify on baremetal, the updated value `bar` is displayed.

**Comment by beefsack** [comment]
Hi @mihaigalos!

Can you output the content of the file running in the container, and check if the file inside the container is updated?

You can do this using something like:

```bash
docker exec -it 3d6e55c660a0 cat /script
```

Sometimes file mounts fail to update in docker containers because some editors use a separate temporary file while editing, then copy it into place once you complete, and Docker won't update the mounted file in the container in cases like this. [This is a known issue with Docker and won't be fixed](https://github.com/moby/moby/issues/15793).

One workaround if you want to use a host mount is to mount a directory instead of the file directly. You could do that using something like:

```bash
docker run -d --rm -p 8080:80 -v /path/to/script/dir:/mnt -e SCRIPT=/mnt/script.sh beefsack/webify
```

**Comment by mihaigalos** [comment]
Oh I see.
I use `vim` which effectively changes the inode because of writing to a separate file and replacing the original, which doesn't reflect in Docker.

Your solution with mounting the whole folder+env var worked - thank you!
